spring.application.name=smart-campus-backend

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=86400000

# MySQL database setting
spring.datasource.url= jdbc:mysql://localhost:3306/segDatabase
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.transaction.jta.platform=org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform
spring.jpa.open-in-view=false

# Server port settings
server.port=8082
server.error.include-message=always
server.error.include-binding-errors=always

# Email sender settings
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=youquanneu4@gmail.com
spring.mail.password=tncc wywu pgdo uvbm
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# H2 Database config for development
# spring.datasource.url=jdbc:h2:mem:
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=
# spring.datasource.password=
# spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 console for development
# spring.h2.console.enabled=true
# spring.h2.console.path=/h2-console

# JPA/Hibernate settings
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true

# CORS configuration (for frontend development)
# Replace with your actual frontend URL
# spring.mvc.cors.allowed-origins=http://localhost:3000
# spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE
# spring.mvc.cors.allowed-headers=*